/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aws.lambda.sample.app;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void testCreateTodo() {
        final var context = new TestContext();
        final var handler = new AppHandler();

        final var input = "A test todo";
        final var output = handler.handleRequest(input, context);
        assert output.task().equals(input);
    }
}
